export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const OPEN_INFO_WINDOW = 'OPEN_INFO_WINDOW';
export const CLOSE_INFO_WINDOW = 'CLOSE_INFO_WINDOW';

export const CHECK_USERNAME_BEGIN = 'CHECK_USERNAME_BEGIN';
export const CHECK_USERNAME_SUCCESS = 'CHECK_USERNAME_SUCCESS';
export const CHECK_USERNAME_ERROR = 'CHECK_USERNAME_ERROR';

export const SIGN_USER_BEGIN = 'SIGN_USER_BEGIN';
export const SIGN_USER_SUCCESS = 'SIGN_USER_SUCCESS';
export const SIGN_USER_ERROR = 'SIGN_USER_ERROR';

export const FORGOT_PASSWORD_BEGIN = 'FORGOT_PASSWORD_BEGIN';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';

export const RESET_PASSWORD_BEGIN = 'RESET_PASSWORD_BEGIN';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER';

export const SET_USER_NOTIFICATIONS_TO_READ = 'SET_USER_NOTIFICATIONS_TO_READ';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

export const ADD_FOODY_BEGIN = 'ADD_FOODY_BEGIN';
export const ADD_FOODY_SUCCESS = 'ADD_FOODY_SUCCESS';
export const ADD_FOODY_ERROR = 'ADD_FOODY_ERROR';

export const GET_FOODYS_BEGIN = 'GET_FOODYS_BEGIN';
export const GET_FOODYS_SUCCESS = 'GET_FOODYS_SUCCESS';

export const SET_FOODYS_ORIGIN = 'SET_FOODYS_ORIGIN';

export const SET_EDIT_FOODY = 'SET_EDIT_FOODY';
export const GET_FOODY_DETAIL = 'GET_FOODY_DETAIL';

export const GET_FOODY_LIKES_BEGIN = 'GET_FOODY_LIKES_BEGIN';
export const GET_FOODY_LIKES_SUCCESS = 'GET_FOODY_LIKES_SUCCESS';
export const GET_FOODY_LIKES_ERROR = 'GET_FOODY_LIKES_ERROR';

export const LIKE_FOODY = 'LIKE_FOODY';
export const UNLIKE_FOODY = 'UNLIKE_FOODY';

export const VISIT_FOODY = 'VISIT_FOODY';
export const UN_VISIT_FOODY = 'UN_VISIT_FOODY';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';

export const UPDATE_FOODY_BEGIN = 'UPDATE_FOODY_BEGIN';
export const UPDATE_FOODY_SUCCESS = 'UPDATE_FOODY_SUCCESS';
export const UPDATE_FOODY_ERROR = 'UPDATE_FOODY_ERROR';

export const DELETE_FOODY_BEGIN = 'DELETE_FOODY_BEGIN';
export const DELETE_FOODY_SUCCESS = 'DELETE_FOODY_SUCCESS';
export const DELETE_FOODY_ERROR = 'DELETE_FOODY_ERROR';

export const CHANGE_FOODY_STATUS = 'CHANGE_FOODY_STATUS';

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN';
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS';

export const CLEAR_FILTERS = 'CLEAR_FILTERS';

export const CHANGE_PAGE = 'CHANGE_PAGE';

export const GET_GOOGLE_API_KEY = 'GET_GOOGLE_API_KEY';

export const SET_USER_HOME_CURRENT_LOCATION = 'SET_USER_HOME_CURRENT_LOCATION';
export const SET_USER_HOME_LOCATION = 'SET_USER_HOME_LOCATION';

export const ADD_FOLLOW_TO_USER_FOLLOWING_STATS =
  'ADD_FOLLOW_TO_USER_FOLLOWING_STATS';
export const REMOVE_FOLLOW_FROM_USER_FOLLOWING_STATS =
  'REMOVE_FOLLOW_FROM_USER_FOLLOWING_STATS';
