export const GET_NOTIFICATIONS_BEGIN = 'GET_NOTIFICATIONS_BEGIN';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_ERROR = 'GET_NOTIFICATIONS_ERROR';

export const DELETE_NOTIFICATION_BEGIN = 'DELETE_NOTIFICATION_BEGIN';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_ERROR = 'DELETE_NOTIFICATION_ERROR';

export const SET_NOTIFICATIONS_TO_READ = 'SET_NOTIFICATIONS_TO_READ';
export const CLEAR_ALERT = 'CLEAR_ALERT';
