export const CLEAR_ALERT = 'CLEAR_ALERT';

export const MARK_CLICKED_ELEMENT = 'MARK_CLICKED_ELEMENT';

export const GET_MY_PROFILE_BEGIN = 'GET_MY_PROFILE_BEGIN';
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';

export const GET_USER_PROFILE_BEGIN = 'GET_USER_PROFILE_BEGIN';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';

export const UPDATE_MY_PROFILE_BEGIN = 'UPDATE_MY_PROFILE_BEGIN';
export const UPDATE_MY_PROFILE_SUCCESS = 'UPDATE_MY_PROFILE_SUCCESS';
export const UPDATE_MY_PROFILE_ERROR = 'UPDATE_MY_PROFILE_ERROR';

export const FOLLOW_USER_BEGIN = 'FOLLOW_USER_BEGIN';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_ERROR = 'FOLLOW_USER_ERROR';

export const UN_FOLLOW_USER_BEGIN = 'UN_FOLLOW_USER_BEGIN';
export const UN_FOLLOW_USER_SUCCESS = 'UN_FOLLOW_USER_SUCCESS';
export const UN_FOLLOW_USER_ERROR = 'UN_FOLLOW_USER_ERROR';

export const GET_FOLLOWERS_BEGIN = 'GET_FOLLOWERS_BEGIN';
export const GET_FOLLOWERS_SUCCESS = 'GET_FOLLOWERS_SUCCESS';

export const GET_FOLLOWING_BEGIN = 'GET_FOLLOWING_BEGIN';
export const GET_FOLLOWING_SUCCESS = 'GET_FOLLOWING_SUCCESS';
